### ISSUE TITLE
Demo for OMOP Mapping Leads

### ISSUE THREAD

**Issue by tursynay** [cladteam/fhir2omop-pm#20]
OMOP Mapping leads asked for a demo early September

**Comment by tursynay** [comment]
Oct 7 -  we will record the demo and share with the OMOP Mapping Leads

**Comment by tursynay** [comment]
Shahim will do the mapping approach
Tanner to talk about semantic (vocab) mapping
Andrew will talk about the implementation of the mapping
Show the final OMOP Mapping
Intermediate tables that we will want to collab with CCDA folks

**Comment by tursynay** [comment]
Hi @ShahimEssaid , @tannerzhang , @laitmana, here is a draft start for a deck: https://docs.google.com/presentation/d/1YuVoF7PUf2IubYKhjWN_Sm-ji8xJtEl1m80Wo91js0M/edit#slide=id.p

**Comment by stephanieshong** [comment]
@stephanieshong - added remaining pipeline steps and brief descriptions 
monocle view of the currently implemented OMOP domains with links.
