### ISSUE TITLE
FHIR to OMOP vocabulary mapping: Identify which attributes have vocabulary values and what bindings, if any, are specified in FHIR R4 or US Core 3.1.1.

### ISSUE THREAD

**Issue by tursynay** [cladteam/fhir2omop-pm#9]
A binding is a statement on the FHIR side that specifies required or preferred vocabularies for a field.

**Comment by tannerzhang** [comment]
For patient resource, 
review of the mapping spec is done. 
Current vocab in preparation in addition to current OMOP/Athena vocab contents:
AdministrativeGender
US Core BirthSex  
OmbRaceCategories
DetailedRace
OmbEthnicityCategories
DetailedEthnicity
AddressUse
AddressType
UspsTwoLetterAlphabeticCodes
Added one more vaocab:
Marital-status

I am in the process of structuring the mapping table for these and will add the mappings for these codes incrementally. May need discussion/decision from the mapping team later. @stephanieshong

**Comment by tannerzhang** [comment]
Patient tag finished. 

Moving to Encounter now.

**Comment by tursynay** [comment]
This is part of the mapping sheet, see #4 , being documented in the sheet. When for example we call encounter done, this will be captured.
There are 3 different tables being used:
- Vocab mapping
- Value set
- Code set map (to harmonize to OMOP or LOINC)

**Comment by tursynay** [comment]
See issue #4

**Comment by stephanieshong** [comment]
@tursynay  - re: your comments two steps above - it should be vocabulary id mapping not vocab mapping( this can be confusing to people reading it.)
